name: plan
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}" -backend-config="key=${{ secrets.BUCKET_KEY }}" -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}"
      - name: plan
        run: terraform plan
