name: plan
on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: gha-sample
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: init
        run: terraform init -backend-config="bucket=${{ secrets.BUCKET_NAME }}" -backend-config="key=${{ secrets.BUCKET_KEY }}" -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}"
      - name: plan
        run: terraform plan | tfnotify plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
